#!/bin/sh


# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

feh --bg-max --image-bg white --no-fehbg ~/wallpaper.png
wmname LG3D
systemctl --user restart polybar.service

if [ "$(autorandr --detect)" = 'work' ]; then
    bspc monitor DP-1 -d I II III IV V
    bspc monitor DP-2 -d VI VII VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         2
bspc config window_gap          7
bspc config top_padding         16

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Emacs state=tiled

bspc rule -a Google-chrome desktop='^1'
bspc rule -a Firefox desktop='^1'
bspc rule -a jetbrains-idea desktop='^3'
bspc rule -a rambox desktop='^4'
bspc rule -a SmartGit desktop='^5'
bspc rule -a Steam desktop='^5'
bspc rule -a libreoffice desktop='^6'
bspc rule -a 'Emacs:scratchpad' state=floating
bspc rule -a 'Termite:scratchpad' state=floating
bspc rule -a "Google Play Music Desktop Player" desktop='^10'
