#!/bin/sh


# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

feh --bg-max --image-bg white --no-fehbg ~/wallpaper.png
wmname LG3D
systemctl --user restart polybar.service

case "$(autorandr --detect)" in
    work)
        bspc monitor DP-1 -d 2 3 5 6 7 8 9
        bspc monitor DP-2 -d 1 4 10
        ;;
    home-prime)
        bspc monitor HDMI-1 -d 1 2 3 5 6 7 8 9
        bspc monitor LVDS-1 -d 4 10
        ;;
    *)
        bspc monitor -d 1 2 3 4 5 6 7 8 9 10
        ;;
esac

bspc config border_width         2
bspc config window_gap          7
bspc config top_padding         16

bspc config split_ratio          0.52
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config focused_border_color '#8BE9FD'

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Emacs state=tiled

bspc rule -a Google-chrome desktop='1'
bspc rule -a Firefox desktop='1'
bspc rule -a jetbrains-idea desktop='3'
bspc rule -a rambox desktop='4'
bspc rule -a SmartGit desktop='5'
bspc rule -a Steam desktop='5'
bspc rule -a libreoffice desktop='6'
bspc rule -a KeePassXC desktop='9'
bspc rule -a "Google Play Music Desktop Player" desktop='10'
bspc rule -a Spotify desktop='10'
bspc rule -a '*:scratchpad' state=floating
