keys:
  - &adomas C120E76F97BBAB21F04B0B11F299EE66602E7FD1
  - &laptop age1x2y06lakj45fatncs8clsnzzkrsj3hl4vdut9qwsd0epuveusqyqk3h26u
  - &work age1davevp82crerwkczlus55cehpr48e3mmpmyx2g6gxg37a8257uasndwpvu
  - &pi age1n7jt7lxh9u26u25ggaltvt3xsjqg8rsaakjcm4lrykzn70l40s0qjp9vqu
  - &t14 age18shz3w4pvxqvagegx50dq8ujcjaq6xa56ptqlqna255xxx4jp9lsu6qjna
  - &pc age1970uksmphn9sggda6mqh32g9nk9tnh6qrxg54rg3dwclrj9vugfscev2uw
  - &t14hm age1dncg28clhzcs75n59k69jsm57vrx30jzy7z72scu7enzc4fyfvaqexs4ns
  - &workhm age1ls4m3p7wvxshrzznldw4t4pp66hsh64qhqamyfz7qlwl8f3c74fs6mqh2r
  - &pihm age14nmypynph4vjumtj7sv3jffvlzmajj8uy8j7s094jhetudchpu4sjrqjvp
  - &pchm age14w94f0ljuaqt03ajw205fje6rl9lglzq5p647uk9nu0h7pt9p5kqlzazka
  - &laptophm age14m9cxe9vtt87dwm3u37cy50vk5yla7tcvsruez24v05yr5yuhvksvpjunw
creation_rules:
  - path_regex: nixos/common-secrets/atuin\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *laptop
          - *pc
          - *pi
          - *t14
          - *work
  - path_regex: nixos/common-secrets/(zerotier|wireguard)\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *pi
  - path_regex: nixos/common-secrets/wireguard/laptop\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *laptop
          - *pi
  - path_regex: nixos/common-secrets/wireguard/work\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *work
          - *pi
  - path_regex: nixos/common-secrets/wireguard/t14\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *t14
          - *pi
  - path_regex: nixos/common-secrets/wireguard/pc\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *pc
          - *pi
  - path_regex: nixos/common-secrets/vpnc\.conf$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *pi
          - *t14
  - path_regex: nixos/home/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *laptop
  - path_regex: nixos/pc/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *pc
  - path_regex: nixos/t14/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *t14
  - path_regex: nixos/work/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *work
  - path_regex: nixos/pi/secrets/[^/]+\.(yaml|env)$
    key_groups:
      - pgp:
          - *adomas
        age:
          - *pi
  - path_regex: hm-secrets/keys\.yaml$
    key_groups:
      - pgp:
          - *adomas
  - path_regex: profiles/cli/atuin/secrets\.yaml$
    key_groups:
      - age:
          - *laptophm
          - *pchm
          - *pihm
          - *t14hm
          - *workhm
