name: Update Flake Inputs

on:
  schedule:
    - cron: '0 2 * * 5'  # At 02:00 on Friday
  workflow_dispatch:

jobs:
  update:
    runs-on: native
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: update flake
      run: nix flake update --commit-lock-file --option access-tokens github.com=${{ secrets.UPDATES_TOKEN }}
    - name: Create Pull Request
      run: |
        git push "https://${PR_TOKEN}@${FORGEJO_SERVER_URL##*/}/${FORGEJO_REPOSITORY}" HEAD:refs/for/master/update-flake-inputs -o force-push=true
      env:
        PR_TOKEN: ${{ secrets.PR_TOKEN }}
