name: Update Flake Inputs

on:
  schedule:
    - cron: '0 2 * * 1,4'  # At 02:00 on Monday and Thursday.
  workflow_dispatch:

jobs:
  update:
    runs-on: native
    steps:
    - uses: actions/checkout@v4
    - name: update flake
      run: nix flake update --commit-lock-file --option access-tokens github.com=${{ secrets.UPDATES_TOKEN }}
    - name: Create Pull Request
      uses: Mai0313/create-pull-request@95b41bb74c7689393eaf7c540f02702d8d41e3e6
      with:
        branch: update-flake-inputs
        token: ${{ secrets.GITEA_TOKEN }}
        github-server-url: git.rpi4.beastade.top
        title: Update flake inputs
