# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "event-lite-0.1.1" = {
      name = "event-lite";
      packageName = "event-lite";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-lite/-/event-lite-0.1.1.tgz";
        sha1 = "47cf08a8d37d0b694cdb7b3b17b51faac6576086";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "ieee754-1.1.12" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.12.tgz";
        sha512 = "0nf551idk1p8slbvd2jvzdh9hkm5z2dpv0b3jh1wgkab3mbi33vimdwiivrymvaqk7ba3by6rg9bn5xsdiqi24cn9vr5yjq6kw8y2qs";
      };
    };
    "int64-buffer-0.1.10" = {
      name = "int64-buffer";
      packageName = "int64-buffer";
      version = "0.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/int64-buffer/-/int64-buffer-0.1.10.tgz";
        sha1 = "277b228a87d95ad777d07c13832022406a473423";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "lodash-4.17.10" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz";
        sha512 = "1ba5b80jjzwrh9fbdk5ywv8sic0dynij21wgrfxsfjzwvwd7x1n6azdhdc0vjdxqmcpm0mhshd1k7n2ascxpz00z3p8a3k97mwg1s2i";
      };
    };
    "msgpack-lite-0.1.26" = {
      name = "msgpack-lite";
      packageName = "msgpack-lite";
      version = "0.1.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/msgpack-lite/-/msgpack-lite-0.1.26.tgz";
        sha1 = "dd3c50b26f059f25e7edee3644418358e2a9ad89";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "traverse-0.6.6" = {
      name = "traverse";
      packageName = "traverse";
      version = "0.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/traverse/-/traverse-0.6.6.tgz";
        sha1 = "cbdf560fd7b9af632502fed40f918c157ea97137";
      };
    };
    "winston-2.4.3" = {
      name = "winston";
      packageName = "winston";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.4.3.tgz";
        sha512 = "2xl32n4m1fmdgpqh1rgbsdchj1cs0y65b2p8zn44m660d41v3ryfpwhlg8f5qyzkg7lq32jpxkzkcqcxk9xhhsj05c9rnpkqg5ax0hr";
      };
    };
  };
  args = {
    name = "neovim";
    packageName = "neovim";
    version = "4.1.0";
    src = ./.;
    dependencies = [
      sources."async-1.0.0"
      sources."colors-1.0.3"
      sources."cycle-1.0.3"
      sources."event-lite-0.1.1"
      sources."eyes-0.1.8"
      sources."ieee754-1.1.12"
      sources."int64-buffer-0.1.10"
      sources."isarray-1.0.0"
      sources."isstream-0.1.2"
      sources."lodash-4.17.10"
      sources."msgpack-lite-0.1.26"
      sources."stack-trace-0.0.10"
      sources."traverse-0.6.6"
      sources."winston-2.4.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Neovim client API and neovim remote plugin provider";
      homepage = https://github.com/neovim/node-client;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}