# This file has been generated by node2nix 1.5.3. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/lodash-4.14.109" = {
      name = "_at_types_slash_lodash";
      packageName = "@types/lodash";
      version = "4.14.109";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/lodash/-/lodash-4.14.109.tgz";
        sha512 = "2zmiqhq1208ggl07q6d70nal5n91x3hdklm955az728f8zh9a03cdd9q5kb6gi350gbpa3dim11hcn2mv4lx6kf4vf3c4ylsd4pr2l6";
      };
    };
    "@types/msgpack-lite-0.1.6" = {
      name = "_at_types_slash_msgpack-lite";
      packageName = "@types/msgpack-lite";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/msgpack-lite/-/msgpack-lite-0.1.6.tgz";
        sha512 = "0q3did2rdmxxi30p25qzmn6mzykbzr5z4bip7i04r6h8qj28n08fdjzyll471dnhm096wk6hrxya2a8xkd37vg1lxxrmdrarz48blb3";
      };
    };
    "@types/node-10.1.2" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "10.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-10.1.2.tgz";
        sha512 = "2jdnzxb8n7a3qjzjckg15vm6ypxcv5df5s1yz9yn4bgr29yaicqdy5i92qc00bnf7yblyagvmzhxs2m10x1aaz9bazjf14rhx23afbf";
      };
    };
    "@types/traverse-0.6.30" = {
      name = "_at_types_slash_traverse";
      packageName = "@types/traverse";
      version = "0.6.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/traverse/-/traverse-0.6.30.tgz";
        sha512 = "3ni8jlrvllmfvndvffnkjcwckk44j5sfvmanf8w3d9cn46gkg3m34z9d7p7nf18pdsb5v38di4hhyaqh135h1163vsvcy9xly5ldqkb";
      };
    };
    "@types/winston-2.3.9" = {
      name = "_at_types_slash_winston";
      packageName = "@types/winston";
      version = "2.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/winston/-/winston-2.3.9.tgz";
        sha512 = "3c6zz4ilybc1ycv2hpkzlywip5hbkxgqv4dgv04v1101ldvnvckc4v9ydvkyq8kmhb7zrijlcgyb88pyll74qr0vp90fdidw5hfwfng";
      };
    };
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "event-lite-0.1.1" = {
      name = "event-lite";
      packageName = "event-lite";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-lite/-/event-lite-0.1.1.tgz";
        sha1 = "47cf08a8d37d0b694cdb7b3b17b51faac6576086";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "ieee754-1.1.11" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.11.tgz";
        sha512 = "0g5x1ijy37vzfz46pnh03mxkmdb9d2qd9f8ncy49xj4j9xkks9p0x8s5hnyc7grwh6sryk118rd7w7wz6w0hzyw9agwnavvlc4g642n";
      };
    };
    "int64-buffer-0.1.10" = {
      name = "int64-buffer";
      packageName = "int64-buffer";
      version = "0.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/int64-buffer/-/int64-buffer-0.1.10.tgz";
        sha1 = "277b228a87d95ad777d07c13832022406a473423";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "lodash-4.17.10" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz";
        sha512 = "1ba5b80jjzwrh9fbdk5ywv8sic0dynij21wgrfxsfjzwvwd7x1n6azdhdc0vjdxqmcpm0mhshd1k7n2ascxpz00z3p8a3k97mwg1s2i";
      };
    };
    "msgpack-lite-0.1.26" = {
      name = "msgpack-lite";
      packageName = "msgpack-lite";
      version = "0.1.26";
      src = fetchurl {
        url = "https://registry.npmjs.org/msgpack-lite/-/msgpack-lite-0.1.26.tgz";
        sha1 = "dd3c50b26f059f25e7edee3644418358e2a9ad89";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "traverse-0.6.6" = {
      name = "traverse";
      packageName = "traverse";
      version = "0.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/traverse/-/traverse-0.6.6.tgz";
        sha1 = "cbdf560fd7b9af632502fed40f918c157ea97137";
      };
    };
    "winston-2.4.2" = {
      name = "winston";
      packageName = "winston";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.4.2.tgz";
        sha512 = "1n2jk29vqjj4v60j3553gyy1lz5mnm90bf999p4nz6chnmh0izg8c9kf4chy1j68fx8d3mnr5ci5llqr4cjy0n775ydjj2zhrvw0bz1";
      };
    };
  };
  args = {
    name = "neovim";
    packageName = "neovim";
    version = "4.0.1";
    src = ./.;
    dependencies = [
      sources."@types/lodash-4.14.109"
      sources."@types/msgpack-lite-0.1.6"
      sources."@types/node-10.1.2"
      sources."@types/traverse-0.6.30"
      sources."@types/winston-2.3.9"
      sources."async-1.0.0"
      sources."colors-1.0.3"
      sources."cycle-1.0.3"
      sources."event-lite-0.1.1"
      sources."eyes-0.1.8"
      sources."ieee754-1.1.11"
      sources."int64-buffer-0.1.10"
      sources."isarray-1.0.0"
      sources."isstream-0.1.2"
      sources."lodash-4.17.10"
      sources."msgpack-lite-0.1.26"
      sources."stack-trace-0.0.10"
      sources."traverse-0.6.6"
      sources."winston-2.4.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Neovim client API and neovim remote plugin provider";
      homepage = https://github.com/neovim/node-client;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}