#!/usr/bin/env bash
# -*- mode: bash-mode; -*-
set -eu

################################################################################
# Edit the following constants and then rename this script to ~/.xmonad/build

# The directory holding your source code and stack.yaml file:
SRC_DIR=~/.config/nixpkgs/home/dotfiles/my-xmonad

# The name of the executable produced by stack.  This comes from the
# executable section of your *.cabal or package.yaml file.
EXE_NAME=my-xmonad

################################################################################

CONFIG_NAME=$SRC_DIR/xmonad.hs
TARGET_EXE=$1

if [ "$TARGET_EXE" -nt $CONFIG_NAME ]; then
    echo "Xmonad executable is newer than config: doing nothing"
    exit 0
fi

# Unset STACK_YAML, to ensure that $SRC_DIR/stack.yaml is used.
unset STACK_YAML

# Do the build.
cd $SRC_DIR
stack build

# Create a hard link at the requested destination, replacing any existing one.
ln -f -T "$(stack exec -- which $EXE_NAME)" "$TARGET_EXE"
