name:                my-xmonad
version:             0.1.0.0

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         My XMonad configuration

dependencies:
- base >= 4.7 && < 5

executables:
  my-xmonad:
    main:                xmonad.hs
    ghc-options:
    - -dynamic
    - -O2
    - -Wall
    - -Werror
    - -fno-warn-missing-signatures
    dependencies:
    - dbus
    - unix
    - utf8-string
    - xmonad
    - xmonad-contrib
