# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "consul-unstable-${version}";
  version = "2016-09-14";
  rev = "a189091a3530051285c12c726ca28ea55e015336";

  goPackagePath = "github.com/hashicorp/consul";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/hashicorp/consul.git";
    sha256 = "04h5y5vixjh9np9lsrk02ypbqwcq855h7l1jlnl1vmfq3sfqjds7";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
