# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "dbxcli-unstable-${version}";
  version = "2019-02-20";
  rev = "a871c88e22f4575d2f2cb1b77af9a91975acd296";

  patches = [ ./keys.patch ];

  goPackagePath = "github.com/dropbox/dbxcli";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/dropbox/dbxcli";
    sha256 = "1cdijn04fwgk7qapbv11v690i77s9j5z0cvbd2qjkp1aldw0figi";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = { };
}
