name: CI
on:
  push:
    branches: [ "master" ]
    paths:
      - '**.nix'
  pull_request:
    branches: [ "**" ]
    paths:
      - '**.nix'
jobs:
  parsing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Nix
        uses: cachix/install-nix-action@v9
        with:
          - skip_adding_nixpkgs_channel: true
      - name: Parsing
        run: './ci/check-nix-files.sh'
